### ISSUE TITLE
(possibly sane) configuration defaults

### ISSUE THREAD

**Issue by posativ** [noqqe/cmddocs#1]
Currently, you can't use cmddocs without a _complete_ configuration. It should be possible to configure just a few options, such as `Datadir` and assume a sane fallback unspecified configuration options.

Also, I suggest to use lowercase sections and configuration options. It is (at least for me) very uncommon to have capitalized configuration options.

Edit: sections are case-insensitive, so it doesn't really matter...

**Comment by noqqe** [comment]
@posativ fixed!
