### ISSUE TITLE
Feature Request/Enhancement: add option for file-extensions (i.e. *.md)

### ISSUE THREAD

**Issue by durcheinandr** [noqqe/cmddocs#11]
It could be useful to have the option to append a file-extension to the filenames.

Benefits:
- While editing editors can use syntax-highlighting (via syntax)
- For viewing editors can be used as pager with syntax-highlighting
- Converting to other formats is easier (i.e. pandoc)
- Formatted viewing of files is possible with other devices (i.e. on Android with [MdReader](https://bitbucket.org/npaul/mdreader))

**Comment by noqqe** [comment]
@durcheinandr what kind of option? Currently you can name files with whatever extension you want.

**Comment by durcheinandr** [comment]
Just an option for a default filename extension. For example: If I want to have `.md` as extension I set an option for `default-extionsion=md` and all new docs will created with this extension automagically added. The extension should be (maybe another option) not visible within cmddocs commands (for example `l`).

(excuse me for bad language)

**Comment by noqqe** [comment]
@durcheinandr ah okay I get what your saying. good idea. will work on it

**Comment by durcheinandr** [comment]
Great. Thanks.
