### ISSUE TITLE
Pip install fails on Manjaro

### ISSUE THREAD

**Issue by Gyges88** [noqqe/cmddocs#15]
Error message below:

[knatterton@desktop ~]$ pip install cmddocs
You are using pip version 7.0.1, however version 7.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting cmddocs
  Downloading cmddocs-0.10.5.tar.gz
Collecting gitpython (from cmddocs)
  Downloading GitPython-1.0.1.tar.gz (355kB)
    100% |████████████████████████████████| 356kB 867kB/s 
Collecting configparser (from cmddocs)
  Downloading configparser-3.3.0r2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 3, in <module>
      File "/usr/lib/python3.4/site-packages/setuptools/**init**.py", line 4, in <module>
        import distutils.core
      File "/usr/lib/python3.4/distutils/core.py", line 18, in <module>
        from distutils.config import PyPIRCCommand
      File "/usr/lib/python3.4/distutils/config.py", line 7, in <module>
        from configparser import ConfigParser
      File "/tmp/pip-build-xcfns1yl/configparser/configparser.py", line 397
        _KEYCRE = re.compile(ur"%(([^)]+))s")
                                             ^
    SyntaxError: invalid syntax

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-xcfns1yl/configparser

**Comment by noqqe** [comment]
cmddocs is currently only working with python2.7. Sorry about that. Could you try "pip2.7 install cmddocs" and run it again?

**Comment by noqqe** [comment]
Also im not sure why pip3 is doing those things. The setup.py clearly states out that python2.7 is the only version thats supported.

**Comment by Gyges88** [comment]
pip2.7 is not installed on my system:
[knatterton@desktop cmddocs-master]$ pip
pip               pip3              pip3.4            pipelight-plugin

However, downloading the zip and running setup with python2.7 works:

[knatterton@desktop cmddocs-master]$ sudo python2.7 setup.py install
running install
running bdist_egg
running egg_info
creating cmddocs.egg-info
writing requirements to cmddocs.egg-info/requires.txt
writing cmddocs.egg-info/PKG-INFO
writing top-level names to cmddocs.egg-info/top_level.txt
writing dependency_links to cmddocs.egg-info/dependency_links.txt
writing entry points to cmddocs.egg-info/entry_points.txt
writing manifest file 'cmddocs.egg-info/SOURCES.txt'
reading manifest file 'cmddocs.egg-info/SOURCES.txt'
writing manifest file 'cmddocs.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/cmddocs
copying cmddocs/**init**.py -> build/lib/cmddocs
copying cmddocs/articles.py -> build/lib/cmddocs
copying cmddocs/completions.py -> build/lib/cmddocs
copying cmddocs/rendering.py -> build/lib/cmddocs
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/cmddocs
copying build/lib/cmddocs/**init**.py -> build/bdist.linux-x86_64/egg/cmddocs
copying build/lib/cmddocs/articles.py -> build/bdist.linux-x86_64/egg/cmddocs
copying build/lib/cmddocs/completions.py -> build/bdist.linux-x86_64/egg/cmddocs
copying build/lib/cmddocs/rendering.py -> build/bdist.linux-x86_64/egg/cmddocs
byte-compiling build/bdist.linux-x86_64/egg/cmddocs/**init**.py to **init**.pyc
byte-compiling build/bdist.linux-x86_64/egg/cmddocs/articles.py to articles.pyc
byte-compiling build/bdist.linux-x86_64/egg/cmddocs/completions.py to completions.pyc
byte-compiling build/bdist.linux-x86_64/egg/cmddocs/rendering.py to rendering.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying cmddocs.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cmddocs.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cmddocs.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cmddocs.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cmddocs.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cmddocs.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cmddocs.egg-info/zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/cmddocs-0.10.3-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing cmddocs-0.10.3-py2.7.egg
Copying cmddocs-0.10.3-py2.7.egg to /usr/lib/python2.7/site-packages
Adding cmddocs 0.10.3 to easy-install.pth file
Installing cmddocs script to /usr/bin

Installed /usr/lib/python2.7/site-packages/cmddocs-0.10.3-py2.7.egg
Processing dependencies for cmddocs==0.10.3
Searching for mistune
Reading https://pypi.python.org/simple/mistune/
Best match: mistune 0.5.1
Downloading https://pypi.python.org/packages/source/m/mistune/mistune-0.5.1.tar.gz#md5=10a42265bfc7e9ad817fe777a4857821
Processing mistune-0.5.1.tar.gz
Writing /tmp/easy_install-GHRZhB/mistune-0.5.1/setup.cfg
Running mistune-0.5.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-GHRZhB/mistune-0.5.1/egg-dist-tmp-xm2r2y
creating /usr/lib/python2.7/site-packages/mistune-0.5.1-py2.7.egg
Extracting mistune-0.5.1-py2.7.egg to /usr/lib/python2.7/site-packages
Adding mistune 0.5.1 to easy-install.pth file

Installed /usr/lib/python2.7/site-packages/mistune-0.5.1-py2.7.egg
Searching for configparser
Reading https://pypi.python.org/simple/configparser/
Best match: configparser 3.5.0b2
Downloading https://pypi.python.org/packages/source/c/configparser/configparser-3.5.0b2.tar.gz#md5=ad2a71db8bd9a017ed4735eac7acfa07
Processing configparser-3.5.0b2.tar.gz
Writing /tmp/easy_install-vF9qkc/configparser-3.5.0b2/setup.cfg
Running configparser-3.5.0b2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-vF9qkc/configparser-3.5.0b2/egg-dist-tmp-0IPM_9
creating /usr/lib/python2.7/site-packages/configparser-3.5.0b2-py2.7.egg
Extracting configparser-3.5.0b2-py2.7.egg to /usr/lib/python2.7/site-packages
Adding configparser 3.5.0b2 to easy-install.pth file

Installed /usr/lib/python2.7/site-packages/configparser-3.5.0b2-py2.7.egg
Searching for gitpython
Reading https://pypi.python.org/simple/gitpython/
Best match: GitPython 1.0.1
Downloading https://pypi.python.org/packages/source/G/GitPython/GitPython-1.0.1.tar.gz#md5=4659644b42c41e5e5170c0cd83ed6422
Processing GitPython-1.0.1.tar.gz
Writing /tmp/easy_install-X_j7Ld/GitPython-1.0.1/setup.cfg
Running GitPython-1.0.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-X_j7Ld/GitPython-1.0.1/egg-dist-tmp-2wr36e
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_requirements'
  warnings.warn(msg)
warning: no files found matching 'README'
creating /usr/lib/python2.7/site-packages/GitPython-1.0.1-py2.7.egg
Extracting GitPython-1.0.1-py2.7.egg to /usr/lib/python2.7/site-packages
Adding GitPython 1.0.1 to easy-install.pth file

Installed /usr/lib/python2.7/site-packages/GitPython-1.0.1-py2.7.egg
Searching for gitdb>=0.6.4
Reading https://pypi.python.org/simple/gitdb/
Best match: gitdb 0.6.4
Downloading https://pypi.python.org/packages/source/g/gitdb/gitdb-0.6.4.tar.gz#md5=44e4366b8bdfd306b075c3a52c96ae1a
Processing gitdb-0.6.4.tar.gz
Writing /tmp/easy_install-UrCV3q/gitdb-0.6.4/setup.cfg
Running gitdb-0.6.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-UrCV3q/gitdb-0.6.4/egg-dist-tmp-NC4ZtH
creating /usr/lib/python2.7/site-packages/gitdb-0.6.4-py2.7-linux-x86_64.egg
Extracting gitdb-0.6.4-py2.7-linux-x86_64.egg to /usr/lib/python2.7/site-packages
Adding gitdb 0.6.4 to easy-install.pth file

Installed /usr/lib/python2.7/site-packages/gitdb-0.6.4-py2.7-linux-x86_64.egg
Searching for smmap>=0.8.5
Reading https://pypi.python.org/simple/smmap/
Best match: smmap 0.9.0
Downloading https://pypi.python.org/packages/source/s/smmap/smmap-0.9.0.tar.gz#md5=d7932d5ace206bf4ae15198cf36fb6ab
Processing smmap-0.9.0.tar.gz
Writing /tmp/easy_install-d5juhl/smmap-0.9.0/setup.cfg
Running smmap-0.9.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-d5juhl/smmap-0.9.0/egg-dist-tmp-NMzfNT
Moving smmap-0.9.0-py2.7.egg to /usr/lib/python2.7/site-packages
Adding smmap 0.9.0 to easy-install.pth file

Installed /usr/lib/python2.7/site-packages/smmap-0.9.0-py2.7.egg
Finished processing dependencies for cmddocs==0.10.3

However, cmmddocs fails in action:

[knatterton@desktop cmddocs-master]$ cmddocs
Successfully created and initialized empty repo at /home/knatterton/Dokumente
cmddocs - press ? for help
cmddocs> ls
Traceback (most recent call last):
  File "/usr/bin/cmddocs", line 9, in <module>
    load_entry_point('cmddocs==0.10.3', 'console_scripts', 'cmddocs')()
  File "build/bdist.linux-x86_64/egg/cmddocs/**init**.py", line 238, in main
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "build/bdist.linux-x86_64/egg/cmddocs/**init**.py", line 100, in do_list
  File "build/bdist.linux-x86_64/egg/cmddocs/articles.py", line 12, in list_articles
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by noqqe** [comment]
Hi,

"tree" is missing. Thats indeed bad. I added an Execption handler for this case, also will add that external dependency to docs.

**Comment by noqqe** [comment]
if you update now from pip, it will handle this error.
