### ISSUE TITLE
When cancelling adding a document, cmddocs crashes

### ISSUE THREAD

**Issue by omgwtflaserguns** [noqqe/cmddocs#30]
Steps to reproduce:
1. edit new document
2. Cancel Editor without saving

**Comment by noqqe** [comment]
mh. cannot reproduce... @ @
![screenshot 2016-04-12 11 40 11](https://cloud.githubusercontent.com/assets/203902/14456206/034d4f7e-00a4-11e6-8820-f65933f46981.png)

Could you explain more detailed what crashes?

**Comment by omgwtflaserguns** [comment]
Cant reproduce anymore, sorry for the inconvenience
